  main = ".open-next/worker.js"
  name = "vitaly-ford-personal-website"
  compatibility_date = "2025-12-30"
  compatibility_flags = ["nodejs_compat"]
  [assets]
  directory = ".open-next/assets"
  binding = "ASSETS"