main = ".open-next/worker.js"
name = "vitaly-ford-personal-site"
compatibility_date = "2025-12-30"
compatibility_flags = ["nodejs_compat"]
keep_vars = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# [vars]
# SCHOLAR_CITATIONS = "721"
# BOOKING_PAGE = "https://calendar.app.google/aHackGAhEtDC9EAW9"
# Note: Set these in Cloudflare dashboard instead